-- Part 1: Test it with SQL
--CREATE TABLE job (
--   column name job_id INTEGER PRIMARY KEY AUTO_INCREMENT,
--   column name job_name VARCHAR(255),
--   column name employer VARCHAR(255),
--   column name skills VARCHAR(255)
--);
-- Part 2: Test it with SQL
--Something here
-- Part 3: Test it with SQL

-- Part 4: Test it with SQL